case 1 "创建operator" 0
CREATE OR REPLACE FUNCTION OSM_FUNC_OP_1(a NUMBER)
  RETURN INTEGER AS
  BEGIN
    IF a > 292 THEN
      RETURN (a-95);
    ELSE
      RETURN (a+63);
    END IF;
  END;
/
CREATE OR REPLACE FUNCTION OSM_FUNC_OP_2(s VARCHAR2)
  RETURN INTEGER AS
  BEGIN
    IF LENGTH(s) > 37 THEN
      RETURN (-50);
    ELSE
      RETURN (91);
    END IF;
  END;
/
CREATE OR REPLACE OPERATOR OSM_DML_OPER
  BINDING (NUMBER) RETURN INTEGER
  USING OSM_FUNC_OP_1,
  (VARCHAR2) RETURN INTEGER USING OSM_FUNC_OP_2;
/


case 2 " Alter Operator" 0
CREATE OR REPLACE FUNCTION OSM_FUNC_OP_1(a NUMBER)
  RETURN INTEGER AS
  BEGIN
    IF a > 292 THEN
      RETURN (a-95);
    ELSE
      RETURN (a+63);
    END IF;
  END;
/
CREATE OR REPLACE FUNCTION OSM_FUNC_OP_2(s VARCHAR2)
  RETURN INTEGER AS
  BEGIN
    IF LENGTH(s) > 37 THEN
      RETURN (-50);
    ELSE
      RETURN (91);
    END IF;
  END;
/
CREATE OR REPLACE FUNCTION OSM_FUNC_OP_3(s VARCHAR2)
  RETURN INTEGER AS
  BEGIN
    IF LENGTH(s) > 77 THEN
      RETURN (-50);
    ELSE
      RETURN (91);
    END IF;
  END;
/
CREATE OR REPLACE OPERATOR OSM_DML_OPER
  BINDING (NUMBER) RETURN INTEGER
  USING OSM_FUNC_OP_1,
  (VARCHAR2) RETURN INTEGER USING OSM_FUNC_OP_2;
/
ALTER OPERATOR OSM_DML_OPER
  ADD BINDING (VARCHAR2) RETURN INTEGER
  USING OSM_FUNC_OP_3;


case 3 " 删除Operator" 0
CREATE OR REPLACE FUNCTION OSM_FUNC_OP_1(a NUMBER)
  RETURN INTEGER AS
  BEGIN
    IF a > 292 THEN
      RETURN (a-95);
    ELSE
      RETURN (a+63);
    END IF;
  END;
/
CREATE OR REPLACE FUNCTION OSM_FUNC_OP_2(s VARCHAR2)
  RETURN INTEGER AS
  BEGIN
    IF LENGTH(s) > 37 THEN
      RETURN (-50);
    ELSE
      RETURN (91);
    END IF;
  END;
/
CREATE OR REPLACE OPERATOR OSM_DML_OPER
  BINDING (NUMBER) RETURN INTEGER
  USING OSM_FUNC_OP_1,
  (VARCHAR2) RETURN INTEGER USING OSM_FUNC_OP_2;
/
DROP OPERATOR Contains FORCE